<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="4" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="HubspotCrm" duration-ms="65621" started-at="2018-10-29T06:00:13Z" finished-at="2018-10-29T06:01:19Z">
    <groups>
    </groups>
    <test name="HomePageTest" duration-ms="65621" started-at="2018-10-29T06:00:13Z" finished-at="2018-10-29T06:01:19Z">
      <class name="com.hubspotcrm.Testcases.HomePageTest">
        <test-method status="PASS" signature="setup()[pri:0, instance:com.hubspotcrm.Testcases.HomePageTest@31ef45e3]" name="setup" is-config="true" duration-ms="7534" started-at="2018-10-29T06:00:13Z" finished-at="2018-10-29T06:00:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="verifyactivityurlTest()[pri:0, instance:com.hubspotcrm.Testcases.HomePageTest@31ef45e3]" name="verifyactivityurlTest" duration-ms="10262" started-at="2018-10-29T06:00:21Z" finished-at="2018-10-29T06:00:31Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyactivityurlTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.hubspotcrm.Testcases.HomePageTest@31ef45e3]" name="tearDown" is-config="true" duration-ms="157" started-at="2018-10-29T06:00:31Z" finished-at="2018-10-29T06:00:31Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setup()[pri:0, instance:com.hubspotcrm.Testcases.HomePageTest@31ef45e3]" name="setup" is-config="true" duration-ms="7090" started-at="2018-10-29T06:00:31Z" finished-at="2018-10-29T06:00:38Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="verifycompaniesurlTest()[pri:0, instance:com.hubspotcrm.Testcases.HomePageTest@31ef45e3]" name="verifycompaniesurlTest" duration-ms="10280" started-at="2018-10-29T06:00:38Z" finished-at="2018-10-29T06:00:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifycompaniesurlTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.hubspotcrm.Testcases.HomePageTest@31ef45e3]" name="tearDown" is-config="true" duration-ms="245" started-at="2018-10-29T06:00:49Z" finished-at="2018-10-29T06:00:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setup()[pri:0, instance:com.hubspotcrm.Testcases.HomePageTest@31ef45e3]" name="setup" is-config="true" duration-ms="5283" started-at="2018-10-29T06:00:49Z" finished-at="2018-10-29T06:00:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="verifycontacturlTest()[pri:0, instance:com.hubspotcrm.Testcases.HomePageTest@31ef45e3]" name="verifycontacturlTest" duration-ms="10552" started-at="2018-10-29T06:00:54Z" finished-at="2018-10-29T06:01:05Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [https://app.hubspot.com/contacts/5068902/contacts/list/view/all/?] but found [https://app.hubspot.com/contacts/5068902/contacts]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [https://app.hubspot.com/contacts/5068902/contacts/list/view/all/?] but found [https://app.hubspot.com/contacts/5068902/contacts]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.hubspotcrm.Testcases.HomePageTest.verifycontacturlTest(HomePageTest.java:41)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifycontacturlTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.hubspotcrm.Testcases.HomePageTest@31ef45e3]" name="tearDown" is-config="true" duration-ms="164" started-at="2018-10-29T06:01:05Z" finished-at="2018-10-29T06:01:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setup()[pri:0, instance:com.hubspotcrm.Testcases.HomePageTest@31ef45e3]" name="setup" is-config="true" duration-ms="4904" started-at="2018-10-29T06:01:05Z" finished-at="2018-10-29T06:01:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="verifylogourlTest()[pri:0, instance:com.hubspotcrm.Testcases.HomePageTest@31ef45e3]" name="verifylogourlTest" duration-ms="8846" started-at="2018-10-29T06:01:10Z" finished-at="2018-10-29T06:01:19Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [https://app.hubspot.com/reports-dashboard/5068902] but found [https://app.hubspot.com/reports-dashboard/5068902/view]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [https://app.hubspot.com/reports-dashboard/5068902] but found [https://app.hubspot.com/reports-dashboard/5068902/view]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.hubspotcrm.Testcases.HomePageTest.verifylogourlTest(HomePageTest.java:36)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifylogourlTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.hubspotcrm.Testcases.HomePageTest@31ef45e3]" name="tearDown" is-config="true" duration-ms="153" started-at="2018-10-29T06:01:19Z" finished-at="2018-10-29T06:01:19Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.hubspotcrm.Testcases.HomePageTest -->
    </test> <!-- HomePageTest -->
  </suite> <!-- HubspotCrm -->
</testng-results>
