<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="4" hostname="Inboundsys-Mac-Dhanalakshmi.local" name="com.hubspotcrm.Testcases.LoginPageTest" tests="5" failures="0" timestamp="13 Nov 2018 07:22:06 GMT" time="0.014" errors="1">
  <testcase name="loginverifyTest" time="0.000" classname="com.hubspotcrm.Testcases.LoginPageTest">
    <skipped/>
  </testcase> <!-- loginverifyTest -->
  <testcase name="setup" time="0.014" classname="com.hubspotcrm.Testcases.LoginPageTest">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.hubspotcrm.base.TestBase.initialization(TestBase.java:40)
at com.hubspotcrm.Testcases.LoginPageTest.setup(LoginPageTest.java:30)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:523)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- setup -->
  <testcase name="verifyPasswordTest" time="0.000" classname="com.hubspotcrm.Testcases.LoginPageTest">
    <skipped/>
  </testcase> <!-- verifyPasswordTest -->
  <testcase name="verifyLinksTest" time="0.000" classname="com.hubspotcrm.Testcases.LoginPageTest">
    <skipped/>
  </testcase> <!-- verifyLinksTest -->
  <testcase name="verifyErrormessageTest" time="0.000" classname="com.hubspotcrm.Testcases.LoginPageTest">
    <skipped/>
  </testcase> <!-- verifyErrormessageTest -->
</testsuite> <!-- com.hubspotcrm.Testcases.LoginPageTest -->
